server:
  port: 8001


spring:
  application:
    name: short-link-project
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: localhost
      port: 6379
      password: Sun1015263819n
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: de17f97261c693e08afdf6df65f4133d
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer，知乎，掘金，博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com

rocketmq:
  name-server: common-rocketmq-dev.magestack.cn:9876
  producer:
    group: short-link_project-service_stats-save_pg_sunguoqiang
    topic: short-link_project-service_topic_sunguoqiang
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
  consumer:
    group: short-link_project-service_stats-save_cg_sunguoqiang
